### ISSUE TITLE
conda install: can't import samap

### ISSUE THREAD

**Issue by jowodo** [atarashansky/SAMap#137]
This is how I installed samap: 
```
conda create -y -n samap-1.0.15 -c bioconda samap=1.0.15
```
Then, I wanted to test it: 
```
conda activate samap-1.0.15
python3 -c 'import samap'
```
This was the output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/samap/__init__.py", line 6, in <module>
    import scanpy as sc
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/scanpy/__init__.py", line 18, in <module>
    from . import datasets, logging, queries, external, get
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/scanpy/external/__init__.py", line 3, in <module>
    from . import pp
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/scanpy/external/pp/__init__.py", line 5, in <module>
    from ._magic import magic
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/scanpy/external/pp/_magic.py", line 7, in <module>
    from legacy_api_wrap import legacy_api
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/legacy_api_wrap.py", line 21, in <module>
    __version__ = get_version(__file__)
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/get_version/__init__.py", line 273, in get_version
    version = method(parent)
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/get_version/__init__.py", line 118, in get_version_from_vcs
    vcs_root = find_vcs_root(parent, vcs=vcs)
  File "/home/apps/conda/miniconda3/envs/samap-1.0.15/lib/python3.7/site-packages/get_version/__init__.py", line 151, in find_vcs_root
    vcs_e = _detect_vcs()
TypeError: _detect_vcs() missing 2 required positional arguments: 'expected_vcs' and 'path'
```

Related: #16

**Comment by jowodo** [comment]
The manual conda install worked nearly as specified in the README. I only had to add `anndata` to the conda packages. 
```
VERSION=1.0.15
URL='https://github.com/atarashansky/SAMap'
DESCRIPTION="SAMap: Mapping single-cell RNA sequencing datasets from evolutionarily distant organisms."
ENVNAME="samap"
LATESTVERSIONCMD='wget -q -O - https://raw.githubusercontent.com/atarashansky/SAMap/main/README.md | head -n1 | cut -d" " -f5'
conda create -y -n $ENVNAME-$VERSION -c conda-forge python=3.9 numpy=1.23.5 pip pybind11 h5py=3.8.0 leidenalg python-igraph texttable anndata # anndata was added here!
conda activate $ENVNAME-$VERSION
mkdir -p $CONDA_PREFIX/share
pushd $CONDA_PREFIX/share
git clone https://github.com/atarashansky/SAMap.git samap.git
pushd samap.git
python3 -m pip install .
popd
popd
```
<details>
<summary> 
`conda list # manual installation` 
</summary>

```
$ conda list
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(188): Could not remove or rename /home/apps/conda/miniconda3/envs/samap-1.0.15/conda-meta/python-igraph-0.11.3-py39h007bc96_1.json.  Please remove this file manually (you may need to reboot to free file handles)
# packages in environment at /home/apps/conda/miniconda3/envs/samap-1.0.15:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anndata                   0.10.3             pyhd8ed1ab_0    conda-forge
arpack                    3.8.0           nompi_h0baa96a_101    conda-forge
array-api-compat          1.4                pyhd8ed1ab_0    conda-forge
bleach                    6.1.0                    pypi_0    pypi
bokeh                     3.2.2                    pypi_0    pypi
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.24.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2023.11.17               pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
colorcet                  3.0.1                    pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
fast-histogram            0.12                     pypi_0    pypi
fonttools                 4.47.0                   pypi_0    pypi
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
h5py                      3.8.0           nompi_py39h89bf01e_101    conda-forge
harmonypy                 0.0.9                    pypi_0    pypi
hdf5                      1.14.0          nompi_hb72d44e_103    conda-forge
hnswlib                   0.7.0                    pypi_0    pypi
holoviews-samap           1.0.1                    pypi_0    pypi
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                      pypi_0    pypi
igraph                    0.10.8                   pypi_0    pypi
importlib-metadata        7.0.0                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
leidenalg                 0.10.1           py39h3d6467e_1    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libleidenalg              0.11.1               h00ab1b0_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.12.3               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
linkify-it-py             2.0.2                    pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
markdown                  3.5.1                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.2                    pypi_0    pypi
mdit-py-plugins           0.4.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
natsort                   8.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
networkx                  3.2.1                    pypi_0    pypi
numba                     0.56.3                   pypi_0    pypi
numpy                     1.23.5           py39h3d75532_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.4            py39hddac248_0    conda-forge
panel                     1.2.3                    pypi_0    pypi
param                     1.13.0                   pypi_0    pypi
patsy                     0.5.4                    pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pybind11                  2.11.1           py39h7633fee_2    conda-forge
pybind11-global           2.11.1           py39h7633fee_2    conda-forge
pyct                      0.5.0                    pypi_0    pypi
pynndescent               0.5.11                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.9.18          h0755675_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyviz-comms               3.0.0                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
sam-algorithm             1.0.2                    pypi_0    pypi
samap                     1.0.15                   pypi_0    pypi
scanpy                    1.9.3                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.11.4           py39h474f0d3_0    conda-forge
seaborn                   0.13.0                   pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
statsmodels               0.14.1                   pypi_0    pypi
stdlib-list               0.10.0                   pypi_0    pypi
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tornado                   6.4                      pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2023c                h71feb2d_0    conda-forge
uc-micro-py               1.0.2                    pypi_0    pypi
umap-learn                0.5.5                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xyzservices               2023.10.1                pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.17.0                   pypi_0    pypi
zstd                      1.5.5                hfc55251_0    conda-forge
```
</details>

**Comment by atarashansky** [comment]
Thanks for the detailed report and the follow-up workaround.

The root cause here is the **bioconda `samap=1.0.15` recipe**, which is third-party maintained and has fallen out of sync — the `get_version`/`legacy_api_wrap` error is a transitive dependency break in that environment, not in SAMap itself.

As of **v3.0.0**, the supported install path is pip:

```bash
conda create -n SAMap -c conda-forge python=3.12 pip
conda activate SAMap
pip install sc-samap
```

v3.0.0 also vendors the SAM algorithm and uses modern dependency pins (`scanpy>=1.10`, `numpy>=1.26`, etc.), so the old `anndata`/`scanpy` resolution issues no longer apply.

We're not currently maintaining the bioconda recipe. If someone wants to submit an updated recipe to bioconda-recipes for v3.0.0, we'd welcome it.

Closing as resolved by v3.0.0 + README update. Thanks!
