### ISSUE TITLE
AttributeError: type object 'object' has no attribute 'dtype'

### ISSUE THREAD

**Issue by pinin4fjords** [atarashansky/SAMap#19]
I'm seeing this issue with the gene pair finding routine:

```
>>> sm = load_samap('hu_mu.run.sam.pkl')
>>> gpf = GenePairFinder(sm,k1=k1,k2=k2)
Finding cluster-specific markers in hu:cell_type and mu:cell_type.
... storing 'cell_type' as categorical
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/lib/python3.7/site-packages/samap/analysis.py", line 98, in __init__
    self.find_markers()
  File "/path/to/lib/python3.7/site-packages/samap/analysis.py", line 108, in find_markers
    find_cluster_markers(self.s1, self.k1)
  File "/path/to/lib/python3.7/site-packages/samap/analysis.py", line 347, in find_cluster_markers
    layer=layer,
  File "/path/to/lib/python3.7/site-packages/scanpy/tools/_rank_genes_groups.py", line 597, in rank_genes_groups
    method, corr_method, n_genes_user, rankby_abs, tie_correct, **kwds
  File "/path/to/lib/python3.7/site-packages/scanpy/tools/_rank_genes_groups.py", line 390, in compute_statistics
    self.stats = pd.DataFrame(columns=idx)
  File "/path/to/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/path/to/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 239, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/path/to/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1449, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
```

I believe this is down to PyPy==1.0.0 (see https://github.com/pandas-dev/pandas/issues/39520). I can see that you've changed the Python pin in https://github.com/atarashansky/self-assembling-manifold/blob/master/setup.py to be '>1.0.0', but it's still '==1.0.0' on PyPi (which is what was used to derive the Conda recipe I'm using).

Could you fix that pin? I'll then update the Conda package and hopefully this goes away. I don't do much PyPi, so not sure if you can just add a new build or if it needs a new version. 

By the way this is another case for the use of GitHub releasses of CI via GitHub actions to keep PyPi in synch without manual PyPi stuff ;-).

**Comment by atarashansky** [comment]
Thanks for reminding me to upload that change to PyPI! I updated the pandas version requirement to solve exactly this issue. The change is up in SAM version 0.8.4 now.
