### ISSUE TITLE
Error in running sm.run()

### ISSUE THREAD

**Issue by FraMont1** [atarashansky/SAMap#95]
Hi Mr. Tarashansky,

Thanks for developing SAMap, this is an amazing tool.

I am writing you because I am trying to run the SAMap_vignette and when I run the sm.run(pairwise=True) command I obtain the following error:

Prepping datasets for translation.
Translating feature spaces pairwise.
Projecting data into joint latent space. 1.8479650020599365
Correcting data with means. 2.2841153144836426
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/francescomonticolo/Desktop/samap_directory/samap/mapping.py", line 298, in run
    smap.run(
  File "/Users/francescomonticolo/Desktop/samap_directory/samap/mapping.py", line 706, in run
    sam4 = _mapper(
  File "/Users/francescomonticolo/Desktop/samap_directory/samap/mapping.py", line 807, in _mapper
    mdata = _mapping_window(sams, gnnm, gn, K=K, pairwise=pairwise)
  File "/Users/francescomonticolo/Desktop/samap_directory/samap/mapping.py", line 1830, in _mapping_window
    output_dict["knn"] = _pairwise_knn(wpca, sams)
  File "/Users/francescomonticolo/Desktop/samap_directory/samap/mapping.py", line 1854, in _pairwise_knn
    b = _united_proj(query, reference, k=k)
NameError: name 'k' is not defined

I also tried using only two dataset but I obtain the same error. 
How could I solve it?
I installed SAMap through the manual installation. Any help would be greatly appreciated.

Thank you for your answer.
Best wishes,
Francesco

**Comment by atarashansky** [comment]
Hi Francesco,

Sorry about that! I accidentally broke `main` with a recent change I was testing.... Please update your local repo (`git pull origin main`) and try installing again! 

Let me know if it still doesn't work,
Best
Alec

**Comment by FraMont1** [comment]
Hi Alec,

Now it works.

Thank you!
Best,
Francesco
